### ISSUE TITLE
Simulation Successful, but Fail on HARP2

### ISSUE THREAD

**Issue by eyeloveu** [OPAE/intel-fpga-bbb#16]
I implemented a message queue from CPU to FPGA with OPAE framework based on the second 
BBB sample project hello_world_mpf. The simulation was successful, but it failed on HARP2. 
Since we cannot utilize SignalTap on HARP2, I decided to print value by reading CSRs. Yet, all the CSRs values read out were 0xffffffff. All I wanna say is WTF!!! -_- Sorry for my emotional words, but this is exactly an FPGA developer's real thought. I think development efficiency and rapid iteration is crucial for the application of FPGA. 
Although my design is not complicated, I am still very confused on where to start on debugging. Now I am trying to add my own logic step by step, with little logic modified on each step, and every single change verified on HARP2, in order to know which step involves errors and make sure the final result is guaranteed. But this is so tedious and low efficiency. Are there any suggestions on feasible efficient methods for debugging?

**Comment by michael-adler** [comment]
HARP questions will get better and faster answers from a larger community at the [HARP forum](https://communities.intel.com/groups/harp).

MMIO (CSRs) that all return -1 is usually a sign that the FPGA or OPAE is in an error state, perhaps even due to a previous user. It could also be your AFU. Failing to respond to an MMIO read request will set an error flag that causes all future reads to return -1.

Did your design meet timing?

Are you using machines at Paderborn University? If so, contacting their mailing list with the failing machine is probably the best option.

**Comment by eyeloveu** [comment]
@michael-adler Yes, I'm using machines at Paderborn University. First, I'm sure that my design met timing. I have checked the timing report every time after P&R finished.  Second, there was nothing wrong with the machine I used. Demo applications could work well. And I check the state of the machine by 'sinfo' every time before I config my GBS.
