### ISSUE TITLE
CCIP Asynchronous Shim C0RX FIFO causing ASE MMIO Read Response timed out.

### ISSUE THREAD

**Issue by zinechant** [OPAE/intel-fpga-bbb#3]
The FIFO for RXC0 is at the size of 1024. A MMIO Read Request could be easily stuck in the FIFO especially when AFU is running slower than 400 MHz. While ASE requires AFU to respond to MMIO Read responses within 512 clocks! So the stuck request would miss the deadline if the asynchronous FIFO is relatively full.
Is this requirement same in the AAL SDK/Kernel?

I can think of two ways to work around:
1. Limit the outstanding cacheline read requests in the AFU.
2. Setup a separate FIFO in the asynchronous shim for MMIO requests. This FIFO would be fed to the inner AFU with higher priority than the cacheline read responses.

But if the software sends the MMIO request too fast, none of them would completely solve the problem. So probably it is also needed to measure the time since the last MMIO call in software.

**Comment by michael-adler** [comment]
You are completely correct. This is a problem we have been discussing for a while. There are two solutions being considered:

1. Increase the timeout by 100x so that it is no longer a problem.
2. Add an alternate path through the async shim so that MMIO reads are favored.

#1 is the preferred solution, and we are looking at whether it is feasible.

I believe that the 512 cycle limit is actually not enforced on Broadwell systems (the Xeon+FPGA systems used in HARPv2). I've built designs for that machine with slow AFUs and with MMIO requests going through the asynchronous shim and haven't seen problems, though the case is not well tested.

More updates later.

**Comment by zinechant** [comment]
@michael-adler Thanks for the reply.

**Comment by michael-adler** [comment]
We have changed the timeout to 128us for future platforms. I believe the HARPv2 systems don't enforce a timeout. You should be able to use the asynchronous shim without modification, even for MMIO read requests.
