### ISSUE TITLE
Simulation scripts generated by setup.ase require manual modications

### ISSUE THREAD

**Issue by MegaStone** [OPAE/intel-fpga-bbb#9]
I am using vcs-2014.03 on Ubuntu 16.04 for simulation. Every time I generate a simulation environment with setup.ase (e.g. run "./sim/setup_ase build" at sample/tutorial/03_linked_list), I have to do some manual modifications under the build directory. 
(1) I have to add "+incdir+../rtl" to SNPS_VLOGAN_OPT so that VCS could find cci_mpf_app_conf.vh
(2) I have to add "-LDFLAGS -Wl,--no-as-needed" to the vcs invocation at Makefile: 487, as discussed in this thread: https://github.com/freechipsproject/rocket-chip/issues/21. I suggest add these flags automatically to vcs when the scripts is invoked on Ubuntu system.

**Comment by michael-adler** [comment]
Thank you for the report. We will try to reproduce the failure and apply your suggestions.

Note that you could update your copy of the Makefile in $OPAE_BASEDIR/ase/Makefile, which is copied by setup_ase, so that you don't have to apply the patch every time.

**Comment by michael-adler** [comment]
I was able to reproduce the +incdir+ problem in vcs-2014.03. It appears to be a VCS bug, failing to find include files when +incdir+ contains an absolute path and the file containing +incdir+ is included with -F. (I'm guessing at the full cause of the bug, though that is the likely problem.) I tried a later version, J-2014.12-SP3-11, and the bug appears to be fixed. So, your solution of "+incdir+../rtl" is not a universal solution since it just happens to fix these workloads that use an "../rtl" path. Note that vcs 2015 versions appear to have changed the arguments to the vcs command and are not yet supported in our build flow, so there is a sweet spot of working simulators if you plan to find a more recent version.

We will consider the Debian/Ubuntu specific problem. I believe, for now, that RedHat derivatives are currently used in the majority of our testing. For this problem, you can safely update the Makefile in your OPAE SDK so that you don't have to edit the Makefile every time you configure a simulation environment.

**Comment by MegaStone** [comment]
Thank you for your response. I will try to update my VCS.
